---
- name: install dependencies
  apt:
    name: "{{ item }}"
    install_recommends: yes
    update_cache: yes
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  become: yes

- name: add repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: yes

- name: add repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    filename: docker
    update_cache: yes
  become: yes

- name: install docker package
  apt:
    name: docker-ce
    install_recommends: yes
    update_cache: yes
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
  become: yes

- name: adding docker group
  group:
    name: docker

- name: adding docker group to users
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ DOCKER_USERS }}"
